name: CI/CD Workflow

on:
  issue_comment:
    types: [created]

jobs:
  build-and-tests:
    if: contains(github.event.comment.body, '/ok-to-test')
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve pull request branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: pull-request-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.pull-request-branch.outputs.head_sha }}
          token: ${{ secrets.GB_TOKEN }}
          status: pending

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pull-request-branch.outputs.head_ref }}

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.pull-request-branch.outputs.head_sha }}
          token: ${{ secrets.GB_TOKEN }}
          status: ${{ job.status }}

  build-and-deploy-sandbox:
    if: contains(github.event.comment.body, '/ok-to-sandbox')
#    needs: [build-and-tests]
    name: Build and Deploy to Sandbox
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve pull request branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: pull-request-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.pull-request-branch.outputs.head_sha }}
          token: ${{ secrets.GB_TOKEN }}
          status: pending

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pull-request-branch.outputs.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

#      - name: Build with Maven
#        run: mvn clean package

#      - name: Build Docker image
#        run: |
#          docker build -t my-app:${{ github.sha }} .
#          docker tag my-app:${{ github.sha }} my-dockerhub-username/my-app:${{ github.sha }}
#
#      - name: Log in to Docker Hub
#        env:
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
#
#      - name: Push Docker image
#        run: docker push my-dockerhub-username/my-app:${{ github.sha }}

      - name: Deploy to Sandbox
        run: |
          # Comando para fazer o deploy na sandbox
          echo "Deploying to sandbox..."

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.pull-request-branch.outputs.head_sha }}
          token: ${{ secrets.GB_TOKEN }}
          status: ${{ job.status }}

